services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  api:
    build:
      context: ./Api
      dockerfile: Dockerfile
    restart: always
    command: npx nodemon Express/src/index.js
    volumes:
      - ./Api/Express:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - backend
      - frontend

  angular:
    build:
      context: ./Angular
      dockerfile: Dockerfile
    command: npx ng serve --host 0.0.0.0 --poll=100
    volumes:
      - ./Angular/AppInventarios:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - frontend

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
