services:
  appinventarios:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "4200:4200"
    container_name: appinventarios-container
    restart: unless-stopped
    volumes:
      - ./AppInventarios:/app
      - /app/node_modules
