SET default_storage_engine = InnoDB;
SET NAMES utf8mb4;

CREATE TABLE passwords (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    password_hash VARCHAR(128) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE departments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE,
    abbreviation VARCHAR(4) NOT NULL UNIQUE,
    description VARCHAR(180),
    department_head VARCHAR(60) NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE floors (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(180) NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE areas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(180),
    type TINYINT UNSIGNED NOT NULL DEFAULT 1,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    id_floor INT UNSIGNED NOT NULL,
    FOREIGN KEY (id_floor) REFERENCES floors(id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    last_name VARCHAR(30) NOT NULL,
    username VARCHAR(25) NOT NULL UNIQUE,
    role TINYINT UNSIGNED NOT NULL DEFAULT 1,
    password_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (password_id) REFERENCES passwords(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE categories (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE,
    description VARCHAR(180) NOT NULL,
    type TINYINT UNSIGNED NOT NULL DEFAULT 1,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1
) ENGINE=InnoDB;

CREATE TABLE device_groups (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    group_number SMALLINT UNSIGNED NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE devices (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    serial_number VARCHAR(50) NOT NULL UNIQUE,
    category_id INT UNSIGNED NOT NULL,
    group_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (category_id) REFERENCES categories(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (group_id) REFERENCES device_groups(id)
        ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE supplies (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(30) NOT NULL,
    product_name VARCHAR(50) NOT NULL,
    stock INT UNSIGNED NOT NULL DEFAULT 0,
    new_stock INT UNSIGNED NOT NULL DEFAULT 0,
    used_stock INT UNSIGNED NOT NULL DEFAULT 0,
    empty_stock INT UNSIGNED NOT NULL DEFAULT 0,
    category_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (category_id) REFERENCES categories(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE supplies_areas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    partial_stock INT UNSIGNED NOT NULL DEFAULT 0,
    new_stock INT UNSIGNED NOT NULL DEFAULT 0,
    used_stock INT UNSIGNED NOT NULL DEFAULT 0,
    empty_stock INT UNSIGNED NOT NULL DEFAULT 0,
    material_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (material_id) REFERENCES supplies(id)
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE guard_rep (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    report_date DATE NOT NULL DEFAULT (CURRENT_DATE),
    name VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(128) NOT NULL,
    group_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (group_id) REFERENCES device_groups(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE checklists (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cpu DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    mouse TINYINT(1) NOT NULL DEFAULT 0,
    keyboard TINYINT(1) NOT NULL DEFAULT 0,
    power TINYINT(1) NOT NULL DEFAULT 0,
    disk TINYINT(1) NOT NULL DEFAULT 0,
    display TINYINT(1) NOT NULL DEFAULT 0,
    fan TINYINT(1) NOT NULL DEFAULT 0,
    virus TINYINT(1) NOT NULL DEFAULT 0,
    windows TINYINT(1) NOT NULL DEFAULT 0,
    paper TINYINT(1) NOT NULL DEFAULT 0,
    temp TINYINT(1) NOT NULL DEFAULT 0,
    free_disk_space TINYINT(1) NOT NULL DEFAULT 0,
    software_np TINYINT(1) NOT NULL DEFAULT 0,
    extensions TINYINT(1) NOT NULL DEFAULT 0,
    defragmentation TINYINT(1) NOT NULL DEFAULT 0,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE leave_records (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    record_date DATE NOT NULL DEFAULT (CURRENT_DATE),
    info VARCHAR(255) NOT NULL,
    detected VARCHAR(255) NOT NULL,
    removal_observations VARCHAR(255) NOT NULL,
    device_id INT UNSIGNED NOT NULL,
    department_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (device_id) REFERENCES devices(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (department_id) REFERENCES departments(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE maintenance_rep (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    maintenance_date DATE NOT NULL DEFAULT (CURRENT_DATE),
    username VARCHAR(50) NOT NULL,
    user_password VARCHAR(128) NOT NULL,
    group_id INT UNSIGNED NOT NULL,
    checklist_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (group_id) REFERENCES device_groups(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (checklist_id) REFERENCES checklists(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;

CREATE TABLE movements (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    movement_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    affected_table VARCHAR(50) NOT NULL,
    change_type TINYINT UNSIGNED NOT NULL,
    after_info TEXT,
    before_info TEXT,
    object_id INT UNSIGNED NOT NULL,
    user_id INT UNSIGNED NOT NULL,
    status TINYINT UNSIGNED NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CHECK (status IN (0,1))
) ENGINE=InnoDB;
